name: Deploy API to stageing

on:
  pull_request:
    branches:
      - dev
jobs:
  api-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/api"
          environment: stageing
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
