name: Build

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter api install --frozen-lockfile

      - name: build
        run: pnpm --filter api build

  build-web:
    name: Build web client
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter web install --frozen-lockfile

      - name: build
        run: pnpm --filter web build
