name: Deploy client

on:
  push:
    branches:
      - main
    paths:
      - apps/client/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: client_production
    name: Deploy
    env:
      PUBLIC_API_URL: ${{ secrets.API_URL }} 
      PROJECT: client
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter $PROJECT install

      - name: Build
        run: pnpm --filter $PROJECT build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: 4.12.0
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/client