name: Migrate stageing db

on:
  push:
    paths:
      - apps/api/src/db/**/schema.ts
    branches:
      - dev

jobs:
  db-migrate-stageing:
    name: DB migrate stageing
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_STAGEING_URL }}
      DB_TOKEN: ${{ secrets.DB_STAGEING_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter api install --frozen-lockfile

      - name: Run migrations
        run: pnpm --filter api db:migrate 
