name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: 4.12.0
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/server