name: Deploy server

on:
  push:
    branches:
      - main
    paths:
      - apps/server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: api-production
    name: Deploy
    env:
      VITE_DB_SYNC_URL: ${{ secrets.DB_URL }}
      VITE_DB_AUTH_TOKEN: ${{ secrets.DB_AUTH_TOKEN }}
      VITE_DEV: false
      VITE_CLIENT_ORIGIN: ${{ secrets.CLIENT_ORIGIN }}
      PROJECT: server
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter $PROJECT install

      - name: Build
        run: pnpm --filter $PROJECT build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: 4.12.0
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/server